version: '3.9'
services:
  demo-backend:
    image:  backend
    restart: always
    environment:
      - PORT=8080
      - LOGLEVEL=debug
    ports:
      - '8080:8080'
  demo-frontend:
    image:
    restart: always
    environment:
      - UIENV=local
    ports:
      - '3000:3000'